package control;

import adt.UserArrayList;
import adt.UserListADT;
import entity.User;
import util.AuthenticationValidator;
import java.util.List;

public class AuthenticationControl {
    private UserListADT userList;
    private User currentUser;
    private User lastCreatedUser;

    public AuthenticationControl() {
        this.userList = new UserArrayList();
        this.currentUser = null;
        initializeStaffAccount();
    }

    private void refreshUserList() {
        this.userList = new UserArrayList();
    }

    private void initializeStaffAccount() {
        // Check if staff account already exists
        if (userList.findUserByEmail("staff@gmail.com") != null) {
            return;
        }
        // Initialize with a default staff account (ID will be auto-generated by UserArrayList)
        User staffAccount = new User(null, "Staff", "staff@gmail.com", "staff123", "STAFF");
        userList.addUser(staffAccount);
    }

    public String login(String email, String password) {
        refreshUserList();

        // Validate input
        String emailError = AuthenticationValidator.validateEmailFormat(email);
        if (!emailError.isEmpty()) {
            return "LOGIN_FAIL: " + emailError;
        }

        String passwordError = AuthenticationValidator.validatePasswordFormat(password);
        if (!passwordError.isEmpty()) {
            return "LOGIN_FAIL: " + passwordError;
        }

        // Check if user exists (case-sensitive email matching)
        User user = null;
        List<User> allUsers = userList.getAllUsers();
        for (User u : allUsers) {
            if (u.getEmail().equals(email)) {
                user = u;
                break;
            }
        }
        
        if (user == null) {
            return "LOGIN_FAIL: User not found. Please register or check your email.";
        }

        if ("removed".equalsIgnoreCase(user.getStatus())) {
            return "LOGIN_FAIL: This account has been removed. Please contact staff.";
        }

        // Verify password (case-sensitive)
        if (!user.getPassword().equals(password)) {
            return "LOGIN_FAIL: Incorrect password.";
        }

        this.currentUser = user;
        return "LOGIN_SUCCESS";
    }

    public String register(String name, String email, String password, String confirmPassword) {
        refreshUserList();

        // Validate name
        String nameError = AuthenticationValidator.validateName(name);
        if (!nameError.isEmpty()) {
            return "REGISTER_FAIL: " + nameError;
        }
        
        // Validate input
        String emailError = AuthenticationValidator.validateEmailFormat(email);
        if (!emailError.isEmpty()) {
            return "REGISTER_FAIL: " + emailError;
        }

        String passwordError = AuthenticationValidator.validatePasswordFormat(password);
        if (!passwordError.isEmpty()) {
            return "REGISTER_FAIL: " + passwordError;
        }

        // Check if passwords match (case-sensitive)
        if (!password.equals(confirmPassword)) {
            return "REGISTER_FAIL: Passwords do not match.";
        }

        // Check if user already exists (case-sensitive)
        if (userList.userExists(email)) {
            return "REGISTER_FAIL: Email already registered. Please login instead.";
        }

        // Create new student account (ID will be auto-generated by UserArrayList)
        User newUser = new User(null, name, email, password, "STUDENT");
        userList.addUser(newUser);
        this.lastCreatedUser = newUser;
        return "REGISTER_SUCCESS";
    }

    public User getLastCreatedUser() {
        return lastCreatedUser;
    }

    public User getCurrentUser() {
        return currentUser;
    }

    public void logout() {
        currentUser = null;
    }

    public boolean isStaff() {
        return currentUser != null && currentUser.getUserType().equals("STAFF");
    }

    public boolean isStudent() {
        return currentUser != null && currentUser.getUserType().equals("STUDENT");
    }
}
